parent(laxmi,nilesh).
parent(suresh,ganga).
parent(nilesh,bhargav).
parent(bhargav,aditya).
parent(suresh,nilesh).
parent(nilesh,nisha).
parent(laxmi,mann).
parent(ganga,jaya).
parent(ganga,priya).
parent(jaya,jay).
parent(gopal,jaya).
parent(priya,pinku).
parent(jatin,jay).
female(laxmi).
female(ganga).
female(nisha).
female(priya).
female(jaya).
female(mani).
female(nila).
male(gopal).
male(mann).
male(jatin).
male(pinku).
male(jay).
male(suresh).
male(nilesh).
male(bhargav).
male(aditya).
wife(nila,nilesh).
wife(laxmi,suresh).
wife(jaya,jatin).
wife(ganga,gopal).
wife(mani,mann).
sister(X,Y):-female(X),parent(Z,X),parent(Z,Y),X\=Y.
brother(X,Y):-male(X),parent(Z,X),parent(Z,Y),X\=Y.
mother(Z,X):-female(Z),parent(Z,X),Z\=X.
father(Z,X):-parent(Z,X),male(Z),Z\=X.
kaka(Y,W):- male(X),male(Y),parent(Z,X),parent(Z,Y),parent(X,W),brother(Y,X),Y\=W.
kaki(W,M):-parent(Z,X),parent(Z,Y),male(X),male(Y),wife(W,Y),parent(X,M),W\=M.
mama(Y,W):-female(X),male(Y),brother(Y,X),parent(Z,X),parent(Z,Y),parent(X,W),Y\=W.
mami(W,M):-parent(Z,X),parent(Z,Y),sister(X,Y),female(X),male(Y),wife(W,Y),parent(X,M),W\=M.
nana(Z,Y):-parent(Z,X),male(Z),female(X),parent(X,Y),Z\=Y.
nani(Z,Y):-parent(Z,X),female(Z),female(X),parent(X,Y),Z\=Y.
son(X,Z):-male(X),parent(Z,X),X\=Z.
daughter(X,Z):-female(X),parent(Z,X),Z\=X.
grandfather(Z,Y):-male(Z),parent(Z,X),male(X),parent(X,Y),Z\=Y.
grandmother(Z,Y):-female(Z),parent(Z,X),male(X),parent(X,Y),Z\=Y.
fua(W,M):-parent(Z,X),male(X),parent(Z,Y),female(Y),parent(X,M),wife(Y,W),W\=M.
foi(Y,W):-parent(Z,X),male(X),parent(Z,Y),female(Y),parent(X,W),Y\=W.
masa(M,W):-parent(Z,X),female(X),parent(Z,Y),female(Y),parent(X,W),sister(Y,X),wife(Y,M),M\=
W.
masi(Y,W):-parent(Z,X),female(X),parent(Z,Y),female(Y),parent(X,W),sister(Y,X),Y\=W.
cousin_brother(Y,M):-parent(Z,X),parent(Z,W),parent(X,Y),parent(W,M),male(Y),X\=W,Y\=M.
cousin_sister(W,M):-parent(Z,X),parent(Z,Y),parent(X,W),female(W),parent(Y,M),X\=Y,W\=
M.

