/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-04-29 18:03:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import java.util.Date;
import java.text.*;

public final class FeedbackStore_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


String butt;
String name;


String sessionUsername;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Logout.jsp", Long.valueOf(1434966448000L));
    _jspx_dependants.put("/TrainingPortalHeader.html", Long.valueOf(1434788270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.sql");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <script type = \"text/javascript\" >\r\n");
      out.write("    history.pushState(null, null, 'FeedbackStore.jsp');\r\n");
      out.write("    window.addEventListener('popstate', function(event) {\r\n");
      out.write("    history.pushState(null, null, 'FeedbackStore.jsp');\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#7FFFD4\"> \r\n");
      out.write("\r\n");

name=(String)session.getAttribute("userName");
butt=request.getParameter("act");
if(butt!=null && butt.equals("-")){
response.sendRedirect("Second.jsp?name="+name+"");
return;

}else{

      out.write('\r');
      out.write('\n');
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t\t\tbody{\r\n");
      out.write("\t\t\tmargin: 0;\r\n");
      out.write("            padding-top: 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<img src=\"./images/PortalHeader.png\" width=\"100%\" height=\"25%\" alt=\"Training Portal\">\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("            .button1\r\n");
      out.write("            {\r\n");
      out.write("            background-image: url('./images/Logout.png');\r\n");
      out.write("\t\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\twidth: 100px;\r\n");
      out.write("\t\t\theight: 50px;\r\n");
      out.write("\t\t\twebkit-background-size: 100% 100%;\r\n");
      out.write("\t\t\t-moz-background-size: 100% 100%;\r\n");
      out.write("\t\t\t-o-background-size: 100% 100%;\r\n");
      out.write("\t\t\tbackground-size: 100% 100%;\r\n");
      out.write("\t\t\tpadding-right: 5px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action='SessionInvalidate.jsp' method='post'>\r\n");
      out.write('\r');
      out.write('\n');

sessionUsername=(String)session.getAttribute("userName");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<input type='submit' value='' class=\"button1\"  onclick=\"return confirm('Are you sure you want to Logout?')\" style=\"float: right; position: relative; top: 15px; right: 10px;\"/>\r\n");
      out.write("</form>\r\n");

out.print("<a href='/Dummy/Second.jsp?name="+sessionUsername+"'><image src='./images/HOMEBUTTON.png' height='50' width='50' padding-right='10' style='float: right; position: relative; right: 20px;'></a>");

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<h2 align=\"center\"><font face=\"verdana\" color=\"maroon\">THANK YOU FOR YOUR PARTICIPATION! </font></h2 >\r\n");

String reqNo=(String)request.getParameter("ReqNo_select");

try {
	
	
String JDBC_DRIVER="",DB_URL="",user_name="",pass="";
	ServletContext context=null;
	
	context = pageContext.getServletContext();
	name=(String)session.getAttribute("userName");
	JDBC_DRIVER = context.getInitParameter("connector_class_name");
	DB_URL = context.getInitParameter("connection_url");
	user_name = context.getInitParameter("username");
	pass = context.getInitParameter("password");
	
	
Class.forName(JDBC_DRIVER);
Connection conn=DriverManager.getConnection(DB_URL,user_name,"");
 

/*boolean flag=false;
			for(int h1=0;h1<13;h1++){
			String s13=request.getParameter(String.valueOf(h1));
			if(s13==null || s13==""){
			flag=true;
			//response.sendRedirect("/Dummy/Feedback.jsp?fieldFill=notFill"); 
			}
			}
			if(flag==true){ */
      out.write("\r\n");
      out.write("\t\t\t<!-- <button type=\"button\" name=\"back\" onclick=\"history.back()\">back</button> -->\r\n");
      out.write("\t\t\t");
//}else{
			String ins="insert into FeedBackDataStore(requestNo) values('"+reqNo+"')";
			PreparedStatement stmt3=conn.prepareStatement(ins);
			stmt3.executeUpdate();
			String arr[]=new String[13];
			for(int h=0;h<13;h++){
			String s1=request.getParameter(String.valueOf(h));
			String addData="update FeedBackDataStore set Question"+(h+1)+"='"+s1+"' where requestNo='"+reqNo+"'";
			//arr[h]=s1;
			PreparedStatement stmt4=conn.prepareStatement(addData);
			stmt4.executeUpdate();
			stmt4=null;
			}
			//DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd hh:mm:ss");
			//Date date = new Date();
			//java.sql.Date AddDate=new java.sql.Date(date.getTime());
			//String ss="update FeedBackDataStore set FeedBackDate='"+AddDate+"' where requestNo='"+reqNo+"'";
			//PreparedStatement stmt5=conn.prepareStatement(ss);
			//stmt5.executeUpdate();
	String url22="update PLMTrainingModuleData set Feedback='yes' where ReqNo='"+ reqNo +"'";		
	PreparedStatement stmt33=conn.prepareStatement(url22);
	stmt33.executeUpdate();
	//out.print("<font size='5' > Go to home page <a href='/Dummy/Second.jsp?name="+name+"'><image src='./images/HOMENEW.jpg' height='50' width='50' ></a></font>");
	//}
}catch(Exception e){
out.print(e);
} 
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
