/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-04-29 18:03:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import java.sql.*;
import javax.sql.*;

public final class RaiseRequest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 String idval=""; 
String refval="";
String val="";

String para=""; 
String moduleFound="";
String name1="";
ResultSet rs=null;
PreparedStatement stmt=null;


String sessionUsername;

 
ResultSet rs1=null;
PreparedStatement stmt1=null;

 String name=""; 
	String JDBC_DRIVER="",DB_URL="",user_name="",pass="";
	ServletContext context=null;
	Connection con = null;	
	
 Connection conn2=null;
ResultSet rs2=null;
PreparedStatement stmt2=null;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/BackButton.html", Long.valueOf(1434951674000L));
    _jspx_dependants.put("/Logout.jsp", Long.valueOf(1434966448000L));
    _jspx_dependants.put("/refresher.jsp", Long.valueOf(1458150918000L));
    _jspx_dependants.put("/SubmitButton.html", Long.valueOf(1434787212000L));
    _jspx_dependants.put("/TrainingPortalHeader.html", Long.valueOf(1434788270000L));
    _jspx_dependants.put("/id.jsp", Long.valueOf(1458139958000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.sql");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script type = \"text/javascript\" >\r\n");
      out.write("    history.pushState(null, null, 'RaiseRequest');\r\n");
      out.write("    window.addEventListener('popstate', function(event) {\r\n");
      out.write("    history.pushState(null, null, 'RaiseRequest');\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("<!-- <script>\r\n");
      out.write("window.location.hash=\"no-back-button\";\r\n");
      out.write("window.location.hash=\"Again-No-back-button\";//again because google chrome don't insert first hash into history\r\n");
      out.write("window.onhashchange=function(){window.location.hash=\"no-back-button\";}\r\n");
      out.write("</script> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<title> Training Portal </title>\r\n");
      out.write("<style>\r\n");
      out.write("function myFunctionId() {\r\n");
 //session.setAttribute("Id","Done");  
   //session.setAttribute("Refresher","");
   val=request.getParameter("raise");

      out.write("\r\n");
      out.write("}\r\n");
      out.write("function myFunctionRefresher() {\r\n");
 //session.setAttribute("Refresher","Done");
   //session.setAttribute("Id","");

      out.write("\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("text-align:center;\r\n");
      out.write("font-family: Cambria;\r\n");
      out.write("font-size: 23px;\r\n");
      out.write("}\r\n");
      out.write("table, td, th {\r\n");
      out.write("\tfont-family: Cambria;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("}\r\n");
      out.write("h1,h2{\r\n");
      out.write("font-family: Cambria;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#2fadbb\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t\t\tbody{\r\n");
      out.write("\t\t\tmargin: 0;\r\n");
      out.write("            padding-top: 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<img src=\"./images/PortalHeader.png\" width=\"100%\" height=\"25%\" alt=\"Training Portal\">\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("            .button1\r\n");
      out.write("            {\r\n");
      out.write("            background-image: url('./images/Logout.png');\r\n");
      out.write("\t\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\twidth: 100px;\r\n");
      out.write("\t\t\theight: 50px;\r\n");
      out.write("\t\t\twebkit-background-size: 100% 100%;\r\n");
      out.write("\t\t\t-moz-background-size: 100% 100%;\r\n");
      out.write("\t\t\t-o-background-size: 100% 100%;\r\n");
      out.write("\t\t\tbackground-size: 100% 100%;\r\n");
      out.write("\t\t\tpadding-right: 5px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action='SessionInvalidate.jsp' method='post'>\r\n");
      out.write('\r');
      out.write('\n');

sessionUsername=(String)session.getAttribute("userName");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<input type='submit' value='' class=\"button1\"  onclick=\"return confirm('Are you sure you want to Logout?')\" style=\"float: right; position: relative; top: 15px; right: 10px;\"/>\r\n");
      out.write("</form>\r\n");

out.print("<a href='/Dummy/Second.jsp?name="+sessionUsername+"'><image src='./images/HOMEBUTTON.png' height='50' width='50' padding-right='10' style='float: right; position: relative; right: 20px;'></a>");

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");

out.print("&nbsp<p text-align='left'><h1 style='display:inline;'><b> W</h1><h2 style='display:inline;'>elcome For Raise Request ");
para=request.getParameter("raise");
moduleFound=request.getParameter("module");
name1=(String)session.getAttribute("userName");
String loc=request.getParameter("location");
String date2=request.getParameter("date");

      out.write("\r\n");
      out.write("<form action=\"raiserequestservlet\" method=\"post\" >\r\n");
 String but=request.getParameter("go");
if(but!=null && but.equals("-")){
response.sendRedirect("Second.jsp?name="+name1+"");
}else{

      out.write("\r\n");
      out.write("<table border=\"0\" align=\"center\">\r\n");
      out.write("<tr><td>\r\n");
      out.write("<input type=\"radio\" name=\"raise\" value=\"Id_creation\" \r\n");
 
//idval=(String)session.getAttribute("Id");
   if (val!=null && val.equals("Id_creation")){ 
      out.write(" \r\n");
      out.write("   checked  \r\n");
 } else { 
      out.write("\r\n");
      out.write("   \r\n");
 } 

      out.write("  onclick=\"myFunctionId()\" >\r\n");
      out.write("</td><td >Id creation</td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td>\r\n");
      out.write("<input type=\"radio\" name=\"raise\" value=\"Refresher_Training\"\r\n");
 
//refval=(String)session.getAttribute("Refresher");
   if (val!=null && val.equals("Refresher_Training")){ 
      out.write(" \r\n");
      out.write("   checked\r\n");
 } else { 
      out.write("\r\n");
      out.write("   \r\n");
   } 

      out.write("\r\n");
      out.write("  onclick=\"myFunctionRefresher()\">\r\n");
      out.write("  </td><td>Refresher Training</font></td></tr>\r\n");
      out.write("  <tr><td align=\"center\" colspan=\"2\">");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("            .button\r\n");
      out.write("            {\r\n");
      out.write("            background-image: url('./images/Sumbit.png');\r\n");
      out.write("\t\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\twidth: 90px;\r\n");
      out.write("\t\t\theight: 30px;\r\n");
      out.write("\t\t\twebkit-background-size: 100% 100%;\r\n");
      out.write("\t\t\t-moz-background-size: 100% 100%;\r\n");
      out.write("\t\t\t-o-background-size: 100% 100%;\r\n");
      out.write("\t\t\tbackground-size: 100% 100%;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<input type=\"submit\" value=\"_\" name=\"act\" class=\"button\">\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("     <!--&nbsp&nbsp&nbsp&nbsp");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("            .button3\r\n");
      out.write("            {\r\n");
      out.write("            background-image: url('./images/back_7.png');\r\n");
      out.write("\t\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\twidth: 90px;\r\n");
      out.write("\t\t\theight: 30px;\r\n");
      out.write("\t\t\twebkit-background-size: 100% 100%;\r\n");
      out.write("\t\t\t-moz-background-size: 100% 100%;\r\n");
      out.write("\t\t\t-o-background-size: 100% 100%;\r\n");
      out.write("\t\t\tbackground-size: 100% 100%;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<input type=\"submit\" value=\"-\" name=\"go\" class=\"button3\">\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("-->\r\n");
      out.write("</td>\r\n");
      out.write("  </tr>\r\n");
      out.write(" </table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
if(para!=null && para.equals("Id_creation")){
try {
String JDBC_DRIVER="",DB_URL="",user_name="",pass="";
ServletContext context=null;
Connection con = null;		
 
 	context = pageContext.getServletContext();
	name1=(String)session.getAttribute("userName");
	JDBC_DRIVER = context.getInitParameter("connector_class_name");
	DB_URL = context.getInitParameter("connection_url");
	user_name = context.getInitParameter("username");
	pass = context.getInitParameter("password");

	  Class.forName(JDBC_DRIVER);
	  con=DriverManager.getConnection(DB_URL,user_name,"");

 
 String s="select * from authentication where Email='"+name1+"' and PersonState='Inactive'";
 stmt=con.prepareStatement(s);
 rs=stmt.executeQuery(); 
 if(rs!=null && rs.next()){ 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title> Training Portal </title>\r\n");
      out.write("<SCRIPT TYPE=\"text/javascript\">\r\n");
      out.write("function populateModule() {\r\n");
      out.write(" \r\n");
      out.write("    var selectedIndexVal = document.getElementById(\"role_select\").selectedIndex;\r\n");
      out.write("    var selectedRoleVal =document.getElementById(\"role_select\").options[selectedIndexVal].value;\r\n");
      out.write(" \r\n");
      out.write("    callFunction(selectedRoleVal);\r\n");
      out.write("   \r\n");
      out.write("  }\r\n");
      out.write(" \r\n");
      out.write("  function callFunction(roleVal){\r\n");
      out.write("  var url=\"populateSubjects.jsp?roleVal=\"+roleVal;\r\n");
      out.write(" \r\n");
      out.write("    var xmlHttp;\r\n");
      out.write("        if (window.XMLHttpRequest) { \r\n");
      out.write(" \r\n");
      out.write("        var xmlHttp = new XMLHttpRequest();\r\n");
      out.write(" \r\n");
      out.write("      } else if (window.ActiveXObject) {\r\n");
      out.write(" \r\n");
      out.write("        var xmlHttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("      }\r\n");
      out.write(" \r\n");
      out.write("    xmlHttp.open('POST', url, true);\r\n");
      out.write("    xmlHttp.onreadystatechange = function() {\r\n");
      out.write(" \r\n");
      out.write("        if (xmlHttp.readyState == 4) {\r\n");
      out.write(" \r\n");
      out.write("            updatepage(xmlHttp.responseText);\r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("    }\r\n");
      out.write("xmlHttp.send(url);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("function updatepage(response){\r\n");
      out.write("document.getElementById(\"Module\").innerHTML = response;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
 
	
	context = pageContext.getServletContext();
	name=(String)session.getAttribute("userName");
	JDBC_DRIVER = context.getInitParameter("connector_class_name");
	DB_URL = context.getInitParameter("connection_url");
	user_name = context.getInitParameter("username");
	pass = context.getInitParameter("password");
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<form action=\"idCreationCheck.jsp\" method=\"post\">\r\n");
      out.write("<table border=\"0\" align=\"center\">\r\n");
      out.write("<tr><td>Location: </td><td>\r\n");
      out.write("<select name=\"location\" id=\"location\">\r\n");
      out.write("          <option value=\"\">-- Select --</option>\r\n");
      out.write("\t\t  <option value=\"Powai\"> Powai </option>\r\n");
      out.write("\t\t  <option value=\"Hazira\"> Hazira </option>\r\n");
      out.write("\t\t  <option value=\"Talegaon\"> Talegaon </option>\r\n");
      out.write("\t\t  <option value=\"Banglore\"> Banglore </option>\r\n");
      out.write("\t\t  <option value=\"Chennai\"> Chennai </option>\r\n");
      out.write("\t\t  <option value=\"Oman\"> Oman </option>\r\n");
      out.write("\t\t  <option value=\"Coimbatore\"> Coimbatore </option>\r\n");
      out.write("\t\t  <option value=\"Ranoli\"> Ranoli </option>\r\n");
      out.write("\t\t  <option value=\"Vizag\"> Vizag </option>\r\n");
      out.write("\t\t  <option value=\"Powai-Marine\"> Powai-Marine </option>\r\n");
      out.write("\t\t  <option value=\"Hazira-Marine\"> Hazira-Marine </option>\r\n");
      out.write("\t\t  <option value=\"Vizag Marine\"> Vizag Marine </option>\r\n");
      out.write("  \r\n");
      out.write("</select> </td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td >Role:</td><td>\r\n");
try{ 


Class.forName(JDBC_DRIVER);
con=DriverManager.getConnection(DB_URL,user_name,"");
	

String s1="select DISTINCT role from PLMTrainingRoleBasedModule";
stmt1=con.prepareStatement(s1);
rs1=stmt1.executeQuery();
			out.print("<select name='role_select' id='role_select' style='width:110px' onchange='populateModule();'>");
            out.print("<option value=''>--Select--</option>");
               
              while (rs1.next()) {
              String  role_name= rs1.getString("role");
              out.print("<option value='"+role_name+"'>"+role_name+"</option>");           
              }
			  out.print("<option value='All'> All Role </option>");
              out.print("</select>");
	}
 catch(Exception e){ 
      out.write("\r\n");
      out.write("\r\n");
 } finally{ 
      out.write("\r\n");
      out.write("\r\n");
 
con.close();
rs1.close();

}
      out.write("\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td> Module :</td><td>\r\n");
      out.write("<div id=\"Module\">\r\n");
      out.write("\r\n");
      out.write("</div></td></tr>\r\n");
      out.write("<tr><td align=\"center\" colspan=\"2\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("            .button\r\n");
      out.write("            {\r\n");
      out.write("            background-image: url('./images/Sumbit.png');\r\n");
      out.write("\t\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\twidth: 90px;\r\n");
      out.write("\t\t\theight: 30px;\r\n");
      out.write("\t\t\twebkit-background-size: 100% 100%;\r\n");
      out.write("\t\t\t-moz-background-size: 100% 100%;\r\n");
      out.write("\t\t\t-o-background-size: 100% 100%;\r\n");
      out.write("\t\t\tbackground-size: 100% 100%;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<input type=\"submit\" value=\"_\" name=\"act\" class=\"button\">\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("</td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write(' ');
 } else { 
		String s1="select * from Authentication where Email='"+name1+"'";
		 stmt=con.prepareStatement(s1);
		 rs=stmt.executeQuery(); 
		 if(rs!=null && rs.next()){ 
		String cur_loc=rs.getString("PersonLocation");
 
	out.print("<font color='white' size='5' face='Cambria'>You have already Id, So you don't allow to create new Id...<br>current location :"+cur_loc+"</font>");
	} 
	}
	}catch(Exception e){
	out.print("exception.."+e);
	} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
} if(moduleFound!=null && moduleFound.equals("notfoundId")) {
out.print("<font color='red' size='5' face='Cambria'>you did not select any module so not allow to create id</font>");
 }

if(para!=null && para.equals("Refresher_Training")){
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<html> \r\n");
      out.write("<head>\r\n");
      out.write("  <link href=\"date_jquery_ui.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"date_jquery_min.js\"></script>\r\n");
      out.write("  <script src=\"date_jquery_ui_min.js\"></script>\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("            .refreshbutton\r\n");
      out.write("            {\r\n");
      out.write("            background-image: url('./images/Sumbit.png');\r\n");
      out.write("\t\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\twidth: 90px;\r\n");
      out.write("\t\t\theight: 30px;\r\n");
      out.write("\t\t\twebkit-background-size: 100% 100%;\r\n");
      out.write("\t\t\t-moz-background-size: 100% 100%;\r\n");
      out.write("\t\t\t-o-background-size: 100% 100%;\r\n");
      out.write("\t\t\tbackground-size: 100% 100%;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("</style>\r\n");
      out.write("  <script>\r\n");
      out.write("\t\t  function myDate(){\r\n");
      out.write("\t\t\tvar datecheck=document.getElementById('datepicker').value;\r\n");
      out.write("\t\t\tdate123 = datecheck;\r\n");
      out.write("\t\t\tif(datecheck.length < 1){\r\n");
      out.write("\t\t\talert(\"date field required..\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar date= new Date(datecheck);\r\n");
      out.write("\t\t\tvar\tsysdate = new Date();\r\n");
      out.write("\t\t\t\tif( sysdate.getTime() > date.getTime() ){\r\n");
      out.write("\t\t\t\talert(\"alteast tomorrow's date must select..\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t  }\r\n");
      out.write("  \r\n");
      out.write("  $(document).ready(function() {\r\n");
      out.write("    $(\"#datepicker\").datepicker();\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  function populateModule() {\r\n");
      out.write(" \r\n");
      out.write("    var selectedIndexVal = document.getElementById(\"role_select\").selectedIndex;\r\n");
      out.write("    var selectedRoleVal =document.getElementById(\"role_select\").options[selectedIndexVal].value;\r\n");
      out.write(" \r\n");
      out.write("    callFunction(selectedRoleVal);\r\n");
      out.write("   \r\n");
      out.write("  }\r\n");
      out.write(" \r\n");
      out.write("  function callFunction(roleVal){\r\n");
      out.write("  var url=\"populateSubjects.jsp?roleVal=\"+roleVal;\r\n");
      out.write(" \r\n");
      out.write("    var xmlHttp;\r\n");
      out.write("        if (window.XMLHttpRequest) { \r\n");
      out.write(" \r\n");
      out.write("        var xmlHttp = new XMLHttpRequest();\r\n");
      out.write(" \r\n");
      out.write("      } else if (window.ActiveXObject) {\r\n");
      out.write(" \r\n");
      out.write("        var xmlHttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("      }\r\n");
      out.write(" \r\n");
      out.write("    xmlHttp.open('POST', url, true);\r\n");
      out.write("    xmlHttp.onreadystatechange = function() {\r\n");
      out.write(" \r\n");
      out.write("        if (xmlHttp.readyState == 4) {\r\n");
      out.write(" \r\n");
      out.write("            updatepage(xmlHttp.responseText);\r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("    }\r\n");
      out.write("xmlHttp.send(url);\r\n");
      out.write("  }\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("function updatepage(response){\r\n");
      out.write("document.getElementById(\"Module\").innerHTML = response;\r\n");
      out.write("}\r\n");
      out.write("</script>  \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<form action=\"DateCheck.jsp\" method=\"post\">\r\n");
      out.write("<table border=\"0\" align=\"center\">\r\n");
      out.write("<tr><td>\r\n");
      out.write("Location: </td>\r\n");
      out.write("<td>\r\n");
      out.write(" <select name=\"location\" id=\"location\">\r\n");
      out.write("          <option value=\"\">-- Select --</option>\r\n");
      out.write("\t\t  <option value=\"Powai\"> Powai </option>\r\n");
      out.write("\t\t  <option value=\"Hazira\"> Hazira </option>\r\n");
      out.write("\t\t  <option value=\"Talegaon\"> Talegaon </option>\r\n");
      out.write("\t\t  <option value=\"Banglore\"> Banglore </option>\r\n");
      out.write("\t\t  <option value=\"Chennai\"> Chennai </option>\r\n");
      out.write("\t\t  <option value=\"Oman\"> Oman </option>\r\n");
      out.write("\t\t  <option value=\"Coimbatore\"> Coimbatore </option>\r\n");
      out.write("\t\t  <option value=\"Ranoli\"> Ranoli </option>\r\n");
      out.write("\t\t  <option value=\"Vizag\"> Vizag </option>\r\n");
      out.write("\t\t  <option value=\"Powai-Marine\"> Powai-Marine </option>\r\n");
      out.write("\t\t  <option value=\"Hazira-Marine\"> Hazira-Marine </option>\r\n");
      out.write("\t\t  <option value=\"Vizag Marine\"> Vizag Marine </option>\r\n");
      out.write("  \r\n");
      out.write("</select> </td></tr><br>\r\n");
      out.write("\r\n");
      out.write("<tr><td>Date: </td><td>   <input type=\"text\" size=\"11\" name=\"datepick\" id=\"datepicker\" /> </td></tr><br>\r\n");
      out.write("\r\n");
      out.write("<tr><td>Role: </td><td>\r\n");
try{ 

String JDBC_DRIVER="",DB_URL="",user_name="",pass="";
	ServletContext context=null;
	
	
	
	context = pageContext.getServletContext();
	name=(String)session.getAttribute("userName");
	JDBC_DRIVER = context.getInitParameter("connector_class_name");
	DB_URL = context.getInitParameter("connection_url");
	user_name = context.getInitParameter("username");
	pass = context.getInitParameter("password");
	
	
Class.forName(JDBC_DRIVER);
conn2=DriverManager.getConnection(DB_URL,user_name,"");
	
String sss="select DISTINCT role from PLMTrainingRoleBasedModule";
stmt2=conn2.prepareStatement(sss);
rs2=stmt2.executeQuery();
			out.print("<select name='role_select' id='role_select' style='width:110px' onchange='populateModule();'>");
            out.print("<option value=''>--Select--</option>");
               
              while (rs2.next()) {
              String  role_name= rs2.getString("role");
              out.print("<option value='"+role_name+"'>"+role_name+"</option>");           
              }
              out.print("</select>");
	}
 catch(Exception e){ 
      out.write("\r\n");
      out.write("\r\n");
 } finally{ 
      out.write("\r\n");
      out.write("\r\n");
 
conn2.close();
rs2.close();

}
      out.write("\r\n");
      out.write("\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td> Module : </td><td>\r\n");
      out.write("<div id=\"Module\"></div> </td></tr><br>\r\n");
      out.write("\r\n");
      out.write("<tr><td colspan=\"2\" align=\"center\"><input type=\"submit\" class=\"refreshbutton\" name=\"submit\" value=\"\" onclick=\"return myDate()\"></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
} if(moduleFound!=null && moduleFound.equals("notfoundModule")) {
out.print("<font color='red' size='5' face='Cambria'>for training you have to select module.</font>");
}
if(loc!=null && loc.equals("notfoundLoc")){
out.print("<font color='red' size='5' face='Cambria'>you did not select Location for training.</font>");
} if(date2!=null && date2.equals("notfoundDate")){
out.print("<font color='red' size='5' face='Cambria'>you did not select Date for training.</font>");
} if(date2!=null && date2.equals("minTodayDate")){
out.print("<font color='red' size='5' face='Cambria'>you can not select past Date for training.</font>");
} if(date2!=null && date2.equals("notProper")){
out.print("<font color='red' size='5' face='Cambria'>please select Date in proper format.</font>");
} 

}
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
