/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-04-29 18:03:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;

public final class Second_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 Connection conn=null;
ResultSet rs=null;
PreparedStatement stmt=null;


String sessionUsername;

 String name=""; 
	String JDBC_DRIVER="",DB_URL="",user_name="",pass="";
	ServletContext context=null;
	Connection con = null;	
	
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/LogoutTest.jsp", Long.valueOf(1435035712000L));
    _jspx_dependants.put("/TrainingPortalHeader.html", Long.valueOf(1434788270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.sql");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--contains 4choice \r\n");
      out.write("if(submit button pressed) then third.java come into pic \r\n");
      out.write("else index.html shows-->\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <script type = \"text/javascript\" >\r\n");
      out.write("    history.pushState(null, null, 'Second');\r\n");
      out.write("    window.addEventListener('popstate', function(event) {\r\n");
      out.write("    history.pushState(null, null, 'Second');\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!--<script>\r\n");
      out.write("window.location.hash=\"no-back-button\";\r\n");
      out.write("window.location.hash=\"Again-No-back-button\";//again because google chrome don't insert first hash into history\r\n");
      out.write("window.onhashchange=function(){window.location.hash=\"no-back-button\";}\r\n");
      out.write("</script>--> \r\n");
      out.write(" <title> Trainig Portal </title> \r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\"> <!-- For intranet testing only, remove in production. for slide show-->\r\n");
      out.write("<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"> <!--for slide show -->\r\n");
      out.write("<script src=\"slideShow.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("p {\r\n");
      out.write("font-size: 20px;\r\n");
      out.write("font-family: Cambria;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("h1{\r\n");
      out.write("font-family: Cambria;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("h2,h3{\r\n");
      out.write("font-family: Cambria;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("table{\r\n");
      out.write("margin-top: 7em;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write(" <link href=\"TableStyle.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write(" <style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("#coolMenu,\r\n");
      out.write("#coolMenu ul {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("\tdisplay:inline;\r\n");
      out.write("}\r\n");
      out.write("#coolMenu{\r\n");
      out.write("\tmargin-left:10;\r\n");
      out.write("}\r\n");
      out.write("#coolMenu {\r\n");
      out.write("    float: left;\r\n");
      out.write("}\r\n");
      out.write("#coolMenu > li {\r\n");
      out.write("    float: left;\r\n");
      out.write("}\r\n");
      out.write("#coolMenu li a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    line-height: 2em;\r\n");
      out.write("    padding: 0 1.5em;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("#coolMenu ul {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    display: none;\r\n");
      out.write("z-index: 999;\r\n");
      out.write("}\r\n");
      out.write("#coolMenu ul li a {\r\n");
      out.write("    width: auto;\r\n");
      out.write("}\r\n");
      out.write("#coolMenu li:hover ul {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("#coolMenu {\r\n");
      out.write("    font-family: Arial;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    background: #E5E5E5;\r\n");
      out.write("}\r\n");
      out.write("#coolMenu > li > a {\r\n");
      out.write("    color: #000;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("#coolMenu > li:hover > a {\r\n");
      out.write("    background: #f09d28;\r\n");
      out.write("    color: #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#coolMenu ul {\r\n");
      out.write("    background: #f09d28;\r\n");
      out.write("}\r\n");
      out.write("#coolMenu ul li a {\r\n");
      out.write("    color: #000;\r\n");
      out.write("}\r\n");
      out.write("#coolMenu ul li:hover a {\r\n");
      out.write("    background: #ffc97c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#eeaf15\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t\t\tbody{\r\n");
      out.write("\t\t\tmargin: 0;\r\n");
      out.write("            padding-top: 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<img src=\"./images/PortalHeader.png\" width=\"100%\" height=\"25%\" alt=\"Training Portal\">\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("            .button1\r\n");
      out.write("            {\r\n");
      out.write("            background-image: url('./images/Logout.png');\r\n");
      out.write("\t\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\twidth: 100px;\r\n");
      out.write("\t\t\theight: 50px;\r\n");
      out.write("\t\t\twebkit-background-size: 100% 100%;\r\n");
      out.write("\t\t\t-moz-background-size: 100% 100%;\r\n");
      out.write("\t\t\t-o-background-size: 100% 100%;\r\n");
      out.write("\t\t\tbackground-size: 100% 100%;\r\n");
      out.write("\t\t\tpadding-right: 5px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action='SessionInvalidate.jsp' method='post'>\r\n");
      out.write('\r');
      out.write('\n');

sessionUsername=(String)session.getAttribute("userName");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<input type='submit' value='' class=\"button1\"  onclick=\"return confirm('Are you sure you want to Logout?')\" style=\"float: right; position: relative; top: 15px; right: 10px;\"/>\r\n");
      out.write("</form>\r\n");

out.print("<a href='/Dummy/Second.jsp?name="+sessionUsername+"'><image src='./images/HOMEBUTTONTEST.png' height='50' width='50' padding-right='10' style='float: right; position: relative; right: 20px;'></a>");

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
 
	
	context = pageContext.getServletContext();
	name=(String)session.getAttribute("userName");
	JDBC_DRIVER = context.getInitParameter("connector_class_name");
	DB_URL = context.getInitParameter("connection_url");
	user_name = context.getInitParameter("username");
	pass = context.getInitParameter("password");
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
 
	//out.print("path : "+request.getRemoteHost());
	//out.print("path : "+request.getServerName()+"port "+request.getServerPort());
	try {

 con = (Connection)context.getAttribute("connection_obj");
 String s="select Name from authentication where Email='"+name+"'";
 stmt=con.prepareStatement(s);
 rs=stmt.executeQuery(); 
 if(rs!=null && rs.next()){
 	out.print("<p text-align='right' ><h1 style='display:inline;'><b> W</h1><h2 style='display:inline;'>elcome  ");
	out.print(rs.getString("Name")+"</h2></b></p><br>");
 }
	 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!--<div  id=\"slideShowImages\"> this is for slide show..\r\n");
      out.write("\t\t\t<img src=\"images/slide1.jpg\" width=\"1010\" height=\"300\" alt=\"Slide 1\"/>\r\n");
      out.write("\t\t\t<img src=\"images/slide2.jpg\" width=\"1010\" height=\"300\" alt=\"Slide 2\" />\r\n");
      out.write("\t\t\t<img src=\"images/slide3.jpg\" width=\"1010\" height=\"300\"  alt=\"Slide 3\" />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t</div>  \r\n");
      out.write("\t<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br> -->\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t");

	//out.print(try123+"request get attr..");
	} catch(Exception e){
	//response.sendError(403,"AccessDenied");
	out.print(e);
	}
	
      out.write("\r\n");
      out.write(" <ul id=\"coolMenu\">\r\n");
      out.write("  <li><a href=\"/Dummy/appearfortest\">Appear For Test</a></li>\r\n");
      out.write(" \r\n");
      out.write("  <li><a href=\"#\">Raise Request</a>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"/Dummy/raiserequestservlet\">Raise Request For Training</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/Dummy/closedrequestshowntouser\"> Show completed request</a></li>\t\r\n");
      out.write("\t</ul></li>\r\n");
      out.write("  <li><a href=\"/Dummy/roleassignment\">Role Assignment</a></li>\r\n");
      out.write("  <li><a href=\"/Dummy/Feedback.jsp\">Feedback Process</a></li>\r\n");
      out.write("  <li><a href=\"http://heintra:1987/SITES/HEDCONNECT/hes/powai/saral_plm/DocPortal/PLM%20Video/Forms/AllItems.aspx\r\n");
      out.write("\">Online Training Module</a></li>\r\n");
      out.write(" </ul>\r\n");
      out.write("\t<!--<table border=\"1\" align=\"right\">\r\n");
      out.write("\t<tr><td>\r\n");
      out.write("\t<div id=\"marque\" style=\"width:200px; lext-align:left; font-size:14px;\">\r\n");
      out.write("\t<strong>LETEST UPDATE</strong>\r\n");
      out.write("\t<marquee onmouseover='this.stop();' onmouseout='this.start();' direction='up' height='180' scrollamount='3'>\r\n");
      out.write("\tany latest update\r\n");
      out.write("\t</marquee>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</td></tr>\r\n");
      out.write("\t</table> -->\r\n");
      out.write("\t\r\n");
      out.write("\t<table class='TFtable' align='center'>\r\n");
      out.write("\t\t");

		try {
		
		String s="select * from PLMTrainingModuleData where UserId='"+name+"' and Attended='no'" ;
		PreparedStatement stmt=con.prepareStatement(s);
		ResultSet rs=stmt.executeQuery();
		out.print("<tr><th align='center' colspan='5'> Pending Request List </th></tr>");
		out.print("<tr><th>Request Number</th><th>Requested Date</th><th>Location</th><th>Role</th><th>Module</th></tr>");
		while(rs.next()){
		String reqNo=rs.getString("ReqNo");
		String ReqDate=rs.getString("ReqDate");
		String loc=rs.getString("Location");
		String role=rs.getString("Role");
		String mod=rs.getString("Module");
		out.print("<tr><td><a href='/Dummy/showDetailToUser.jsp?Request="+reqNo+"'>"+reqNo+"</td><td>"+ReqDate+"</td><td>"+loc+"</td><td>"+role+"</td><td>"+mod+"</td></tr>");
		}
		}catch(Exception e){
		out.print(e);
		}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
